# Generated by Django 6.0.3 on 2026-03-06 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='NONE', max_length=4)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to='machine.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machine.workshop'),
        ),
        migrations.CreateModel(
            name='BreakDownMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RP', 'Reported'), ('ST', 'Started'), ('ED', 'Ended')], max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('break_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='machine.breakdown')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['time'], name='machine_bre_time_f7d08b_idx'), models.Index(fields=['status'], name='machine_bre_status_feb75e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='breakdown',
            index=models.Index(fields=['-date_added'], name='machine_bre_date_ad_42c881_idx'),
        ),
    ]
