# Generated by Django 6.0.3 on 2026-05-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='break_down',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machine.breakdown'),
        ),
        migrations.AddField(
            model_name='breakdownmove',
            name='break_down',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='machine.breakdown'),
        ),
        migrations.AddField(
            model_name='breakdownmove',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='closing_break_down_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.closingbreakdowntypes'),
        ),
        migrations.AddField(
            model_name='currentworkshop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currentworkshop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machine.department'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='machinenotes',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='responsible_for_breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.responsibleforbreakdown'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsibleforbreakdown',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.workshop'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.workshop'),
        ),
        migrations.AddField(
            model_name='currentworkshop',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentworkshop', to='machine.workshop'),
        ),
        migrations.AddField(
            model_name='closingbreakdowntypes',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.workshop'),
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshopparticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshopparticipant', to='machine.workshop'),
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['created_at'], name='machine_bre_created_419cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['status'], name='machine_bre_status_feb75e_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['break_down', '-created_at'], name='machine_bre_break_d_3e8e12_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdown',
            index=models.Index(fields=['-created_at'], name='machine_bre_created_f41390_idx'),
        ),
    ]
