# Generated by Django 6.0.3 on 2026-03-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_breakdownmove_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='phase_id',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='MachineNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1025)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='machine.machine')),
            ],
        ),
    ]
