# Generated by Django 6.0.3 on 2026-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machine_phase_id_machinenotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='LOW', max_length=4),
        ),
    ]
