# Generated by Django 6.0.3 on 2026-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machinenotes_created_by_machinenotes_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinenotes',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='machinenotes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='machine/notes'),
        ),
    ]
