# Generated by Django 6.0.3 on 2026-04-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_currentworkshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='workshop',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='priority',
            field=models.CharField(choices=[('NONE', 'None'), ('MID', 'Mid'), ('HIGH', 'High')], default='NONE', max_length=4),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='machine.workshop')),
            ],
        ),
    ]
