# Generated by Django 6.0.3 on 2026-04-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_rename_workshop_machine_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='machine.workshop'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machine.department'),
        ),
    ]
