# Generated by Django 6.0.3 on 2026-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_alter_department_workshop_alter_machine_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='phase_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
