# Generated by Django 6.0.3 on 2026-05-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_alter_machine_phase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingBreakdownTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleForBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEndingBreakDownInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_down', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machine.breakdown')),
                ('closing_break_down_type', models.ManyToManyField(to='machine.closingbreakdowntypes')),
                ('responsible_for_breakdown', models.ManyToManyField(to='machine.responsibleforbreakdown')),
            ],
        ),
    ]
