# Generated by Django 6.0.3 on 2026-05-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_closingbreakdowntypes_responsibleforbreakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='machine.machine'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['break_down', '-time'], name='machine_bre_break_d_8dccd9_idx'),
        ),
    ]
