# Generated by Django 6.0.3 on 2026-05-01 18:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_alter_breakdown_machine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdownmove',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='breakdown',
            name='machine_bre_date_ad_42c881_idx',
        ),
        migrations.RemoveIndex(
            model_name='breakdownmove',
            name='machine_bre_time_f7d08b_idx',
        ),
        migrations.RemoveIndex(
            model_name='breakdownmove',
            name='machine_bre_break_d_8dccd9_idx',
        ),
        migrations.RenameField(
            model_name='breakdown',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='breakdownmove',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='breakdownmove',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='closingbreakdowntypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closingbreakdowntypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='currentworkshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentworkshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machinenotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinenotes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='responsibleforbreakdown',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsibleforbreakdown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='breakdown',
            index=models.Index(fields=['-created_at'], name='machine_bre_created_f41390_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['created_at'], name='machine_bre_created_419cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmove',
            index=models.Index(fields=['break_down', '-created_at'], name='machine_bre_break_d_3e8e12_idx'),
        ),
    ]
