# Generated by Django 6.0.3 on 2026-05-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_alter_breakdownmove_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalendingbreakdowninfo',
            name='closing_break_down_type',
        ),
        migrations.RemoveField(
            model_name='additionalendingbreakdowninfo',
            name='responsible_for_breakdown',
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='closing_break_down_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.closingbreakdowntypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalendingbreakdowninfo',
            name='responsible_for_breakdown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.responsibleforbreakdown'),
            preserve_default=False,
        ),
    ]
