# Generated by Django 6.0.3 on 2026-05-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Novice', 'P1'), ('Beginner', 'P2'), ('Intermediate', 'P3'), ('Advanced', 'P4')], max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('card_nfc', models.CharField(max_length=255)),
                ('card_scan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('who_train', models.CharField(max_length=255)),
                ('who_exam', models.CharField(max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='operatorknowlage.operatoruser')),
            ],
        ),
    ]
