# Generated by Django 6.0.3 on 2026-08-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0002_alter_currentdepartment_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedulePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('shift_duration_hours', models.PositiveIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_presets', to='ur.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='ur.workschedulepreset')),
            ],
            options={
                'ordering': ['start_time', 'order'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='ur.workschedulepreset'),
        ),
    ]
