# Generated by Django 6.0.3 on 2026-08-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0003_workschedulepreset_schedulebreak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='work_schedule',
        ),
        migrations.RemoveField(
            model_name='workschedulepreset',
            name='workshop',
        ),
        migrations.AddField(
            model_name='workschedulepreset',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ur.machine'),
        ),
        migrations.AlterField(
            model_name='workschedulepreset',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
