# Generated by Django 6.0.3 on 2026-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0004_remove_machine_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='phase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
