# Generated by Django 6.0.3 on 2026-09-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0005_alter_machine_phase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineNoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='machine/notes')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ur.machinenotes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
