# Generated by Django 6.0.3 on 2026-04-22 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_maintenancepermissions_maintenancerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_page',
            field=models.CharField(choices=[('BREAKDOWN', 'Break Down'), ('BREAKDOWN_CRATE', 'Break Down Create'), ('ADMIN_PAGE', 'Admin page')], default='BREAKDOWN_CRATE', max_length=255),
        ),
        migrations.CreateModel(
            name='AppsRoleBGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(related_name='approles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerole',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintroles', to='user.appsrolebgs'),
        ),
        migrations.DeleteModel(
            name='MaintenancePermissions',
        ),
    ]
