# Generated by Django 6.0.3 on 2026-04-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_main_page_appsrolebgs_maintenancerole_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerole',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maintroles', to='user.appsrolebgs'),
            preserve_default=False,
        ),
    ]
